############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 5

[[main]]
name = "ECA"
url = "eca/"
weight = 2

[[main]]
name = "Blogs"
url = "blog/"
weight = 4

# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true

#   [[main]]
#   parent = "Pages"
#   name = "Blog Details"
#   url = "blog/post-1/"
#   weight = 1

[[main]]
name = "FAQs"
url = "faqs/"
weight = 3

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5

# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Blog"
# url = "blog/"
# weight = 2

# [[footer]]
# name = "Blog Details"
# url = "blog/post-1/"
# weight = 3

# [[footer]]
# name = "Terms & Conditions"
# url = "terms-and-conditions/"
# weight = 4
